# Generated by Django 5.1.7 on 2025-03-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food_consume',
            new_name='food_consumed',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='protien',
            new_name='protein',
        ),
    ]
